const images = {
Zelda:{
  0: new Image().src = "../docs/zelda/tile0.jpg",
  1: new Image().src = "../docs/zelda/tile1.jpg",
  2: new Image().src = "../docs/zelda/tile2.jpg",
  3: new Image().src = "../docs/zelda/tile3.jpg",
  4: new Image().src = "../docs/zelda/tile4.jpg",
  5: new Image().src = "../docs/zelda/tile5.jpg",
  6: new Image().src = "../docs/zelda/tile6.jpg",
  7: new Image().src = "../docs/zelda/tile7.jpg",
  8: new Image().src = "../docs/zelda/tile8.jpg",
  9: new Image().src = "../docs/zelda/tile9.jpg",
  10:new Image().src = "../docs/zelda/tile10.jpg",
  11:new Image().src = "../docs/zelda/tile11.jpg",
  12:new Image().src = "../docs/zelda/tile12.jpg",
  13:new Image().src = "../docs/zelda/tile13.jpg",
  14:new Image().src = "../docs/zelda/tile14.jpg",
  15:new Image().src = "../docs/zelda/tile15.jpg",
  16:new Image().src = "../docs/zelda/tile16.jpg",
  17:new Image().src = "../docs/zelda/tile17.jpg",
  18:new Image().src = "../docs/zelda/tile18.jpg",
  19:new Image().src = "../docs/zelda/tile19.jpg",
  20:new Image().src = "../docs/zelda/tile20.jpg",
  21:new Image().src = "../docs/zelda/tile21.jpg",
  22:new Image().src = "../docs/zelda/tile22.jpg",
  23:new Image().src = "../docs/zelda/tile23.jpg",
  24:new Image().src = "../docs/zelda/tile24.jpg",
  25:new Image().src = "../docs/zelda/tile25.jpg",
  26:new Image().src = "../docs/zelda/tile26.jpg",
  27:new Image().src = "../docs/zelda/tile27.jpg",
  28:new Image().src = "../docs/zelda/tile28.jpg",
  29:new Image().src = "../docs/zelda/tile29.jpg",
  30:new Image().src = "../docs/zelda/tile30.jpg",
  31:new Image().src = "../docs/zelda/tile31.jpg",

},
Cracks:{
  0:new Image().src = "../docs/cracks/crack00.png",
  1:new Image().src = "../docs/cracks/crack01.png",
  2:new Image().src = "../docs/cracks/crack02.png",
  3:new Image().src = "../docs/cracks/crack03.png",
  4:new Image().src = "../docs/cracks/crack04.png",
}

}